# Generated by Django 4.1.7 on 2023-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1985-05-31'),
            preserve_default=False,
        ),
    ]
