# Generated by Django 4.2 on 2023-07-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartIterm',
            new_name='CartItem',
        ),
    ]
